/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Tabulation.Graphical_User_Interface.Client_Module;

import Tabulation.Additional_Implements.Insert2_gen_ranks;
import Tabulation.Additional_Implements.Insert_results;
import Tabulation.Additional_getters.Generated_ranks;
import Tabulation.Additional_getters.View_Cul_Ranks;
import Tabulation.Additional_getters.View_gen_id;
import Tabulation.Additonal_Interface.Add_results;
import Tabulation.Additonal_Interface.add_generated_ranks;
import Tabulation.Additonal_methods.Generate_ranks;
import Tabulation.Additonal_methods.Select_Ranks;
import Tabulation.Additonal_methods.Select_count;
import Tabulation.Additonal_methods.Select_gen_id;
import Tabulation.Connections.Center_Frame;
import Tabulation.Interface.Add_OverAllSpo_Score;
import Tabulation.Interface.Add_SportScore;
import Tabulation.Interface.Implementation.Add_OverSpo_Imple;
import Tabulation.Interface.Implementation.Add_Spo_Score_Imple;
import Tabulation.Methods.Select_Commands.View_Parti;
import Tabulation.Methods.Select_Commands.View_Sports_Events;
import Tabulation.Methods.Select_Commands.queryattended;
import Tabulation.getters_setters.Attended_CulturalEvents;
import Tabulation.getters_setters.Participant;
import Tabulation.getters_setters.Result_sub;
import Tabulation.getters_setters.Sport_Event;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AL AMRY
 */
public class A_FinalForm_Sport extends javax.swing.JFrame {
int row;
 int dec;
    /**
     * Creates new form FinalForm
     */
    public A_FinalForm_Sport() {
        initComponents();
        Lb_score.setText("");
       new Center_Frame().Center(this);

        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        tab_sub = new javax.swing.JLabel();
        tab_cul = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cul_id = new javax.swing.JLabel();
        sub_id = new javax.swing.JLabel();
        ace_id = new javax.swing.JLabel();
        cul = new javax.swing.JLabel();
        ace = new javax.swing.JLabel();
        cb_part = new javax.swing.JLabel();
        cb_tem = new javax.swing.JLabel();
        spid = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        v_Ima2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        id_num = new javax.swing.JTextField();
        fulln = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        teamN = new javax.swing.JTextField();
        teamnum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Lb_score = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel12 = new javax.swing.JLabel();
        view_eve = new javax.swing.JTextField();
        tage = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        crt_id = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tms = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jLabel10 = new javax.swing.JLabel();
        one = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        ate = new javax.swing.JButton();
        five = new javax.swing.JButton();
        two = new javax.swing.JButton();
        six = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        three = new javax.swing.JButton();
        back = new javax.swing.JButton();
        tol = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        four = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_hist = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconImage( Toolkit.getDefaultToolkit().getImage(getClass().getResource("tablogo.gif")));
        setResizable(false);

        tab_sub.setBounds(0, 0, 0, 0);
        jLayeredPane1.add(tab_sub, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tab_cul.setBounds(0, 0, 0, 0);
        jLayeredPane1.add(tab_cul, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        jPanel1.setOpaque(false);

        jLabel8.setBackground(new java.awt.Color(102, 102, 255));
        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Enter Your Score");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jLabel8.setOpaque(true);

        cul_id.setForeground(new java.awt.Color(204, 204, 204));

        sub_id.setForeground(new java.awt.Color(204, 204, 204));

        ace_id.setForeground(new java.awt.Color(204, 204, 204));

        cul.setForeground(new java.awt.Color(204, 204, 204));

        ace.setForeground(new java.awt.Color(204, 204, 204));

        cb_part.setForeground(new java.awt.Color(204, 204, 204));

        cb_tem.setForeground(new java.awt.Color(204, 204, 204));

        spid.setForeground(new java.awt.Color(204, 204, 204));

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        v_Ima2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v_Ima2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 4, true));
        v_Ima2.setBounds(30, 60, 144, 144);
        jLayeredPane2.add(v_Ima2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Participant Information");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setBounds(0, 0, 590, 31);
        jLayeredPane2.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel15.setText("ID Number:");
        jLabel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel15.setBounds(200, 60, 90, 30);
        jLayeredPane2.add(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        id_num.setEditable(false);
        id_num.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        id_num.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        id_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_numActionPerformed(evt);
            }
        });
        id_num.setBounds(290, 60, 230, 30);
        jLayeredPane2.add(id_num, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fulln.setEditable(false);
        fulln.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        fulln.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        fulln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnActionPerformed(evt);
            }
        });
        fulln.setBounds(290, 90, 230, 30);
        jLayeredPane2.add(fulln, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel4.setText("Full Name:");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setBounds(200, 90, 90, 30);
        jLayeredPane2.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel5.setText("Team Name:");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setBounds(200, 120, 90, 30);
        jLayeredPane2.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        teamN.setEditable(false);
        teamN.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        teamN.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        teamN.setBounds(290, 120, 230, 30);
        jLayeredPane2.add(teamN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        teamnum.setEditable(false);
        teamnum.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        teamnum.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        teamnum.setBounds(290, 150, 230, 30);
        jLayeredPane2.add(teamnum, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel6.setText("Number:");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel6.setBounds(200, 150, 90, 30);
        jLayeredPane2.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Score:");
        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel11.setBounds(200, 180, 90, 30);
        jLayeredPane2.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Lb_score.setBackground(new java.awt.Color(0, 0, 0));
        Lb_score.setEditable(false);
        Lb_score.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Lb_score.setForeground(new java.awt.Color(153, 153, 255));
        Lb_score.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Lb_score.setBounds(290, 180, 150, 30);
        jLayeredPane2.add(Lb_score, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton14.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tabulation/Image/Icon/Add.png"))); // NOI18N
        jButton14.setText("Add");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jButton14.setBounds(440, 180, 80, 30);
        jLayeredPane2.add(jButton14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Selected Event");
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel12.setBounds(0, 0, 300, 30);
        jLayeredPane3.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        view_eve.setEditable(false);
        view_eve.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        view_eve.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        view_eve.setOpaque(false);
        view_eve.setBounds(110, 40, 170, 30);
        jLayeredPane3.add(view_eve, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tage.setBackground(new java.awt.Color(0, 0, 0));
        tage.setEditable(false);
        tage.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        tage.setForeground(new java.awt.Color(153, 153, 255));
        tage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tage.setBounds(110, 70, 170, 30);
        jLayeredPane3.add(tage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel16.setText("Percentage:");
        jLabel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel16.setBounds(10, 70, 100, 30);
        jLayeredPane3.add(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel17.setText("Event Name:");
        jLabel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel17.setBounds(10, 40, 100, 30);
        jLayeredPane3.add(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        crt_id.setBounds(220, 110, 50, 17);
        jLayeredPane4.add(crt_id, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Select Team Number");
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel14.setBounds(0, 0, 280, 29);
        jLayeredPane4.add(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tms.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tms.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Here!!!" }));
        tms.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tmsItemStateChanged(evt);
            }
        });
        tms.setBounds(120, 50, 145, 30);
        jLayeredPane4.add(tms, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel13.setText("Team Number:");
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel13.setBounds(20, 50, 100, 30);
        jLayeredPane4.add(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Select Your Score");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel10.setBounds(0, 0, 590, 31);
        jLayeredPane5.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        one.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });
        one.setBounds(70, 40, 90, 60);
        jLayeredPane5.add(one, javax.swing.JLayeredPane.DEFAULT_LAYER);

        seven.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });
        seven.setBounds(70, 160, 90, 60);
        jLayeredPane5.add(seven, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ate.setText("8");
        ate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ateActionPerformed(evt);
            }
        });
        ate.setBounds(180, 160, 90, 60);
        jLayeredPane5.add(ate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        five.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });
        five.setBounds(180, 100, 90, 60);
        jLayeredPane5.add(five, javax.swing.JLayeredPane.DEFAULT_LAYER);

        two.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });
        two.setBounds(180, 40, 90, 60);
        jLayeredPane5.add(two, javax.swing.JLayeredPane.DEFAULT_LAYER);

        six.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });
        six.setBounds(290, 100, 90, 60);
        jLayeredPane5.add(six, javax.swing.JLayeredPane.DEFAULT_LAYER);

        nine.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });
        nine.setBounds(290, 160, 90, 60);
        jLayeredPane5.add(nine, javax.swing.JLayeredPane.DEFAULT_LAYER);

        three.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        three.setText("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });
        three.setBounds(290, 40, 90, 60);
        jLayeredPane5.add(three, javax.swing.JLayeredPane.DEFAULT_LAYER);

        back.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        back.setText("Clear");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        back.setBounds(400, 160, 90, 60);
        jLayeredPane5.add(back, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tol.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tol.setText(".");
        tol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tolActionPerformed(evt);
            }
        });
        tol.setBounds(400, 100, 90, 60);
        jLayeredPane5.add(tol, javax.swing.JLayeredPane.DEFAULT_LAYER);

        zero.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });
        zero.setBounds(400, 40, 90, 60);
        jLayeredPane5.add(zero, javax.swing.JLayeredPane.DEFAULT_LAYER);

        four.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });
        four.setBounds(70, 100, 90, 60);
        jLayeredPane5.add(four, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        jPanel6.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Score History");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tab_hist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tab_hist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Sport Event", "Given Score", "Computed Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab_hist.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tab_hist);

        jButton1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tabulation/Image/Icon/close.png"))); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane4))
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(jLayeredPane5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spid, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cul_id, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(sub_id, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ace_id, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(cul, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ace, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(363, 363, 363)
                .addComponent(cb_part, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(cb_tem, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(sub_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                                        .addComponent(cul_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ace_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                                        .addComponent(cul, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                                        .addComponent(ace, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                                    .addComponent(cb_part, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_tem, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                    .addComponent(jLayeredPane4)))
                            .addComponent(spid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.setBounds(0, 0, 1360, 760);
        jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1363, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        
        Lb_score.setText("");
        dec = 0;
    }//GEN-LAST:event_backActionPerformed

    private void fullnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        // TODO add your handling code here:
        Lb_score.setText(Lb_score.getText()+one.getText());
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:
        Lb_score.setText(Lb_score.getText()+two.getText());
    }//GEN-LAST:event_twoActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        // TODO add your handling code here:
        Lb_score.setText(Lb_score.getText()+three.getText());
    }//GEN-LAST:event_threeActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        // TODO add your handling code here:
        Lb_score.setText(Lb_score.getText()+four.getText());
    }//GEN-LAST:event_fourActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        // TODO add your handling code here:
        Lb_score.setText(Lb_score.getText()+zero.getText());
    }//GEN-LAST:event_zeroActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        // TODO add your handling code here:
        Lb_score.setText(Lb_score.getText()+five.getText());
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        // TODO add your handling code here:
        Lb_score.setText(Lb_score.getText()+six.getText());
    }//GEN-LAST:event_sixActionPerformed

    private void tolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tolActionPerformed
        // TODO add your handling code here:
        if (dec == 0){
            Lb_score.setText(Lb_score.getText()+tol.getText());
            dec = 1;

        }
    }//GEN-LAST:event_tolActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        // TODO add your handling code here:
        Lb_score.setText(Lb_score.getText()+seven.getText());
    }//GEN-LAST:event_sevenActionPerformed

    private void ateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ateActionPerformed
        // TODO add your handling code here
        Lb_score.setText(Lb_score.getText()+ate.getText());
    }//GEN-LAST:event_ateActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        // TODO add your handling code here:
        Lb_score.setText(Lb_score.getText()+nine.getText());
    }//GEN-LAST:event_nineActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    
        String t_num = teamnum.getText();
        String c_id = spid.getText();
        
        String pp = teamnum.getText();
        String oo = Lb_score.getText();
        //String a = (tab_hist.getModel().getValueAt(row, 1).toString());
        DefaultTableModel model1=(DefaultTableModel)tab_hist.getModel();
       String test = tage.getText();
        String tts = Lb_score.getText();
       
            
        if(test.equals("")|| tts.equals("")){
            JOptionPane.showMessageDialog(null,"Please Enter Your Score"); 
            
        }
       
        
       
            try{
                double g_s = Double.parseDouble(Lb_score.getText());
               // DefaultTableModel model10=(DefaultTableModel)tab_crt.getModel();
                
                
                
        double per = Double.parseDouble(tage.getText());
        
        double score = g_s * per;
         
         
         model1.addRow(new Object[]{
            t_num,c_id,g_s,score
        });
        
        Lb_score.setText("");
        
        dec =0;
       
        crt_id.setText("");
        
      
        
        } catch(Exception e){;}
        
            
        
       
            
            
       // if (a.equals(c_id) ){
       //     JOptionPane.showMessageDialog(null, "hhh");
       // }
        
       
        
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model=(DefaultTableModel)tab_hist.getModel();
          //DefaultTableModel model1=(DefaultTableModel)tab_crt.getModel();
          Result_sub mm = new Result_sub();
          
        
         
         
       
          
      double sum = 0;
      
      String tm = teamnum.getText();
      
      
      String cul = cul_id.getText();
      String sub = sub_id.getText();
      
             
        int row1 = tab_hist.getRowCount();
        int column = tab_hist.getColumnCount();
        int acee = Integer.parseInt(ace_id.getText());
        try {
                 String gg;
                 String gg1;
                 String gg2;
                     
                     Object[] val =new Object[column];

                for (int k = 0; k < val.length - 3; k++) {

                for (int j = 0; j < row1; j++) {

                for (int i = 0; i < column; i++) {

               
             val[0] = tab_hist.getValueAt(j,3);
             val[1] = tab_hist.getValueAt(j,1);
             val[2] = tab_hist.getValueAt(j,2);
             
                }
                gg  = val[0].toString();
                gg1 = val[1].toString();
                gg2 = val[2].toString();
                
                try{
                    
                    Add_SportScore cs = new Add_Spo_Score_Imple();
                    cs.Sports_Score(Double.parseDouble(gg2),acee,Double.parseDouble(gg));
                   
                }catch(Exception e){JOptionPane.showMessageDialog(null,e);}
                
                
                 Add_OverAllSpo_Score css = new Add_OverSpo_Imple();
                    css.Overall_Sport(Double.parseDouble(gg),acee);
                }
                
                
                 
           
                
                   
                
                 
        
                JOptionPane.showMessageDialog(null,"Sucessful");
                jButton1.setBackground(null);
                model.setRowCount(0);
            
                }
                
                
                
                List<Generated_ranks> sList11 = new ArrayList<>();
           Generate_ranks p11 =new Generate_ranks();
           Select_count ss = new Select_count();
           int cultu_id = Integer.parseInt(spid.getText());
            List<View_Cul_Ranks> sList12= new ArrayList<>();
           Select_Ranks p12 =new Select_Ranks();
           List<View_gen_id> sList15= new ArrayList<>();
           Select_gen_id p15 = new Select_gen_id();
           int cosid =0;
           int id = 0;
           int j = 0;
           try {
               
            int num = ss.View_rks();
             sList11= p11.Gen_rak_sport(cultu_id);
             sList12= p12.View_rks_sport();
        for (int i=0;i<sList11.size();i++){
           cosid = sList11.get(i).getCos_id();
           id = sList12.get(i).getId();
           add_generated_ranks AD = new Insert2_gen_ranks();
           AD.gen_ranks_sport(cosid,id);
           //delete_gen_ranks hh = new Insert_gen_ranks();
           // hh.Update(id);
       
        }
        
        sList15 = p15.View_gen_sport();
        String gen_id = null;
        for (int i =0;i<sList15.size();i++){
            gen_id = sList15.get(i).getId();
            Add_results dd = new Insert_results();
        dd.results(null,gen_id);
        }
        
        
          
       
        
           } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        
        }catch (Exception ex) {
                JOptionPane.showMessageDialog(null,ex);
            }
        
        
        tms.setEnabled(true);
        tms.setSelectedItem("Select Here!!!");
        tms.removeItem(Integer.parseInt(tm)); 
        
       
        
    
   
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void id_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_numActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        cb_part.setText("0");
        cb_tem.setText("0");
        Sport_Scorer nn = new Sport_Scorer();

        nn.setVisible(true);
        nn.home.setVisible(false);
        Sport_Scorer.scorer.setVisible(true);
       DefaultTableModel model=(DefaultTableModel)Sport_Scorer.tab_eve.getModel();
       String empty =Sport_Scorer.ser_ve.getText();
       
      // DefaultTableModel model1=(DefaultTableModel)tab_sub.getModel();
       
      // if (model1.getRowCount() != 0){
        //    model1.setRowCount(0);
      // }
        
       //String empty = ser_eve.getText();
       if (model.getRowCount() != 0){
            model.setRowCount(0);
        }
       
        List<Sport_Event> sList = new ArrayList<Sport_Event>();   
        
        View_Sports_Events p =new  View_Sports_Events();
        
         try {
            sList = p.View_spo();
          
            for (int i=0;i<sList.size();i++){
            model.addRow(new Object[]{});
            Sport_Scorer.tab_eve.setValueAt(sList.get(i).getSp_ID(), i, 0);
            Sport_Scorer.tab_eve.setValueAt(sList.get(i).getSp_Name(), i, 1);
            Sport_Scorer.tab_eve.setValueAt(sList.get(i).getSp_Percentage(), i, 2);
            
            Sport_Scorer.tab_eve.setValueAt(sList.get(i).getSp_Status(), i, 3);
        }
       
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tmsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tmsItemStateChanged
        // TODO add your handling code here:
          List<Participant> sList2 = new ArrayList<>();
        String ccls = spid.getText();
        String am = tms.getSelectedItem().toString();
        String ttnm = teamnum.getText();
        
       
       View_Parti p2 = new View_Parti();
        
        try {
            sList2 = p2.ViewParti_sports(ccls,am);
          
            for (int i=0;i<sList2.size();i++){
              
              String tn = sList2.get(i).getTeam();
              int pn = sList2.get(i).getId();
              
              fulln.setText("---------------N/A---------------");
              teamN.setText(tn);
              teamnum.setText(am);
              id_num.setText(""+pn);
              tms.setEnabled(false);
              
          
            
        }
       
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        
        
         List<Attended_CulturalEvents> sList = new ArrayList<>();
        queryattended p = new queryattended();
        try {
            sList = p.queryattend_Sport(ccls, ttnm);
          
            for (int i=0;i<sList.size();i++){
              
              int tn = sList.get(i).getCul_ID();
              ace_id.setText(""+tn);
        }
       
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_tmsItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A_FinalForm_Sport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A_FinalForm_Sport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A_FinalForm_Sport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A_FinalForm_Sport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new A_FinalForm_Sport().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Lb_score;
    public static javax.swing.JLabel ace;
    public static javax.swing.JLabel ace_id;
    private javax.swing.JButton ate;
    private javax.swing.JButton back;
    public static javax.swing.JLabel cb_part;
    public static javax.swing.JLabel cb_tem;
    private javax.swing.JLabel crt_id;
    public static javax.swing.JLabel cul;
    public static javax.swing.JLabel cul_id;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JTextField fulln;
    private javax.swing.JTextField id_num;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    public static javax.swing.JLabel spid;
    public static javax.swing.JLabel sub_id;
    private javax.swing.JLabel tab_cul;
    private javax.swing.JTable tab_hist;
    private javax.swing.JLabel tab_sub;
    public static javax.swing.JTextField tage;
    private javax.swing.JTextField teamN;
    private javax.swing.JTextField teamnum;
    private javax.swing.JButton three;
    public static javax.swing.JComboBox tms;
    private javax.swing.JButton tol;
    private javax.swing.JButton two;
    public static javax.swing.JLabel v_Ima2;
    public static javax.swing.JTextField view_eve;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
