/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Tabulation.Graphical_User_Interface.Client_Module;

import Tabulation.Graphical_User_Interface.Administrator_Module.login;
import Tabulation.Interface.Implementation._AddCriteriaScoreImplementation;
import Tabulation.Interface._AddCriteriaScore;
import Tabulation.Methods.Select_Commands.*;
import Tabulation.getters_setters.Cultural_Event;
import Tabulation.getters_setters.Participant;
import Tabulation.getters_setters.Sport_Event;
import Tabulation.getters_setters.Team;
import java.awt.CardLayout;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neil
 */
public class Sport_window extends javax.swing.JFrame implements ActionListener{
Timer clockTimer;
    /**
     * Creates new form Sport_window
     */
    public Sport_window() {
        initComponents();
        date1.setText(getDate());
        clockTimer = new Timer(1000,this );
        clockTimer.start();
        percent.hide();partid.hide();
        teamid.hide();SPlid.hide();
        getReference1();
        this.setLocationRelativeTo(null);
        
    }
    public String getDate()
   {
      DateFormat dateFormat = new SimpleDateFormat( "MMMMMMMMM d, yyyy" );
      Calendar calendar = Calendar.getInstance();
      return dateFormat.format( calendar.getTime() );
   }
     private void getReference1(){
        try{
        List<Cultural_Event> sList= new ArrayList<>();
        Query_Set_Rank p =new Query_Set_Rank();
        
        sList= p.queryCultural_EventName();
        for (int i=sList.size()-1;i>=0;i--){
          String rank = sList.get(i).getCul_Name();
          ranks.addItem(rank);
          
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
     
     public void getteaminfo(){
         try{
        DefaultTableModel model=(DefaultTableModel)teams.getModel();
        model.setRowCount(0);
         
        List<Team> sList = new ArrayList<>();
        query_Team_Name QTN =new query_Team_Name();
        sList = QTN.qeury_team_name();
            for (int i=0;i<sList.size();i++){
            model.addRow(new Object[]{});
            teams.setValueAt(sList.get(i).getTeam_ID(), i, 0);
            teams.setValueAt(sList.get(i).getTeam_Name(), i, 1);
            teams.setValueAt(sList.get(i).getTeam_Number(), i, 2);
            }
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
     }
     
     public void getspevent(){
          DefaultTableModel model=(DefaultTableModel)spevent.getModel();
        model.setRowCount(0);
     
     List<Sport_Event> sList = new ArrayList<Sport_Event>();   
        
        View_Sports_Events p =new  View_Sports_Events();
        
         try {
            sList = p._getsportevent();
          
            for (int i=0;i<sList.size();i++){
            model.addRow(new Object[]{});
            spevent.setValueAt(sList.get(i).getSp_ID(), i, 0);
            spevent.setValueAt(sList.get(i).getSp_Name(), i, 1);
            spevent.setValueAt(sList.get(i).getSp_Percentage(), i, 2);
            spevent.setValueAt(sList.get(i).getSp_Type(), i, 3);
        }
         }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        culturalname1 = new javax.swing.JLabel();
        time1 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        cuturalid1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        scoring = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel90 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        spevent = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel93 = new javax.swing.JLabel();
        timage = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        teams = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        part = new javax.swing.JTable();
        jLabel95 = new javax.swing.JLabel();
        pimage = new javax.swing.JLabel();
        SPlid = new javax.swing.JLabel();
        teamid = new javax.swing.JLabel();
        partid = new javax.swing.JLabel();
        percent = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel92 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ranks = new javax.swing.JComboBox();
        score = new javax.swing.JTextField();
        compute = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel91 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        history = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sports Window");
        setIconImage( Toolkit.getDefaultToolkit().getImage(getClass().getResource("tablogo.gif")));
        setResizable(false);

        main.setLayout(new java.awt.CardLayout());

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 255, 0));
        jLabel1.setFont(new java.awt.Font("Cooper Black", 1, 60)); // NOI18N
        jLabel1.setForeground(java.awt.Color.green);
        jLabel1.setText("Tap for Scoring");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tabulation/Image/tablogo1.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel39.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel39.setText("User Login:");

        culturalname1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        culturalname1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        culturalname1.setText("jLabel39");

        time1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        time1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel41.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel41.setText("Date:");

        jLabel43.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel43.setText("Time:");

        date1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        date1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cuturalid1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cuturalid1.setText("ID");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cuturalid1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(culturalname1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(time1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(date1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(time1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cuturalid1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(culturalname1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator2)
        );

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                .addContainerGap(416, Short.MAX_VALUE)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(435, 435, 435))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(410, 410, 410))))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        main.add(home, "card2");

        scoring.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255)));

        jLabel90.setBackground(new java.awt.Color(102, 102, 255));
        jLabel90.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel90.setForeground(new java.awt.Color(255, 255, 255));
        jLabel90.setText("Sports Event");
        jLabel90.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jLabel90.setOpaque(true);

        spevent.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        spevent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Event Name", "Percentage", "Event Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spevent.setFillsViewportHeight(true);
        spevent.setShowHorizontalLines(false);
        spevent.setShowVerticalLines(false);
        spevent.getTableHeader().setReorderingAllowed(false);
        spevent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                speventMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(spevent);
        spevent.getColumnModel().getColumn(0).setResizable(false);
        spevent.getColumnModel().getColumn(1).setResizable(false);
        spevent.getColumnModel().getColumn(2).setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel90, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255)));

        jLabel93.setBackground(new java.awt.Color(102, 102, 255));
        jLabel93.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(255, 255, 255));
        jLabel93.setText("Teams Information");
        jLabel93.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jLabel93.setOpaque(true);

        timage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        timage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timage.setText("No Image Available");
        timage.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 4, true), "Team Picture"));

        teams.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        teams.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Team", "Team Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        teams.setFillsViewportHeight(true);
        teams.setShowHorizontalLines(false);
        teams.setShowVerticalLines(false);
        teams.getTableHeader().setReorderingAllowed(false);
        teams.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teamsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(teams);
        teams.getColumnModel().getColumn(0).setResizable(false);
        teams.getColumnModel().getColumn(1).setResizable(false);
        teams.getColumnModel().getColumn(2).setResizable(false);

        part.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        part.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Participant N ame", "Gender", "Team"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        part.setFillsViewportHeight(true);
        part.setShowHorizontalLines(false);
        part.setShowVerticalLines(false);
        part.getTableHeader().setReorderingAllowed(false);
        part.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                partMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(part);
        part.getColumnModel().getColumn(0).setResizable(false);
        part.getColumnModel().getColumn(1).setResizable(false);
        part.getColumnModel().getColumn(2).setResizable(false);
        part.getColumnModel().getColumn(3).setResizable(false);

        jLabel95.setBackground(new java.awt.Color(102, 102, 255));
        jLabel95.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(255, 255, 255));
        jLabel95.setText("Participants");
        jLabel95.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jLabel95.setOpaque(true);

        pimage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pimage.setText("No Image Available");
        pimage.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 4, true), "Participant Pricture"));

        percent.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel93, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
            .addComponent(jLabel95, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(SPlid)
                        .addComponent(teamid)
                        .addComponent(partid))
                    .addComponent(percent, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timage, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(pimage, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addComponent(jScrollPane4)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SPlid)
                        .addGap(16, 16, 16)
                        .addComponent(teamid)
                        .addGap(17, 17, 17)
                        .addComponent(partid))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(timage, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pimage, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel95, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(percent, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255)));

        jLabel92.setBackground(new java.awt.Color(102, 102, 255));
        jLabel92.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel92.setForeground(new java.awt.Color(255, 255, 255));
        jLabel92.setText("Scoring Area");
        jLabel92.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jLabel92.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel2.setText("Rank:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel3.setText("Score:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel4.setText("Computed Score:");

        ranks.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        ranks.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select-Rank-:" }));

        score.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        score.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        score.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                scoreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                scoreKeyTyped(evt);
            }
        });

        compute.setEditable(false);
        compute.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        compute.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tabulation/Image/Icon/save.png"))); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel92, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ranks, 0, 326, Short.MAX_VALUE)
                    .addComponent(score)
                    .addComponent(compute)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel92, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ranks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(compute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255)));

        jLabel91.setBackground(new java.awt.Color(102, 102, 255));
        jLabel91.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(255, 255, 255));
        jLabel91.setText("History");
        jLabel91.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jLabel91.setOpaque(true);

        history.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        history.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rank", "Score", "Event", "Team"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        history.setFillsViewportHeight(true);
        history.setShowHorizontalLines(false);
        history.setShowVerticalLines(false);
        history.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(history);
        history.getColumnModel().getColumn(0).setResizable(false);
        history.getColumnModel().getColumn(1).setResizable(false);
        history.getColumnModel().getColumn(2).setResizable(false);
        history.getColumnModel().getColumn(2).setPreferredWidth(200);
        history.getColumnModel().getColumn(3).setResizable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel91, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel91, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout scoringLayout = new javax.swing.GroupLayout(scoring);
        scoring.setLayout(scoringLayout);
        scoringLayout.setHorizontalGroup(
            scoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scoringLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        scoringLayout.setVerticalGroup(
            scoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scoringLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        main.add(scoring, "card3");

        jMenu1.setBackground(new java.awt.Color(0, 255, 0));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tabulation/Image/Icon/Actions-office-chart-pie-icon.png"))); // NOI18N
        jMenu1.setText("Action");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tabulation/Image/Icon/Actions-go-home-icon.png"))); // NOI18N
        jMenuItem1.setText("Home");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tabulation/Image/Icon/system-log-out.png"))); // NOI18N
        jMenuItem2.setText("Logout");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) main.getLayout();
        cl.show(main, "card2");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        int dialog = JOptionPane.showConfirmDialog(null, "Do you want to close the system?", "Prompt Window", JOptionPane.YES_NO_OPTION);
        if (dialog == JOptionPane.YES_OPTION) {
            dispose();
            new login().show();
        } else if (dialog == JOptionPane.NO_OPTION) {
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) main.getLayout();
        cl.show(main,"card3");
        getteaminfo();
        getspevent();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) main.getLayout();
        cl.show(main,"card3");
        getteaminfo();
        getspevent();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) main.getLayout();
        cl.show(main,"card3");
        getteaminfo();
        getspevent();
    }//GEN-LAST:event_homeMouseClicked

    private void speventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_speventMouseClicked
        // TODO add your handling code here:
        List<Participant> sList = new ArrayList<Participant>();   
        DefaultTableModel model1=(DefaultTableModel)part.getModel();
        int row = spevent.getSelectedRow();
        String TableClick = (spevent.getModel().getValueAt(row, 0).toString());
        String TableClick1 = (spevent.getModel().getValueAt(row, 2).toString());
        View_Parti p =new  View_Parti();
        model1.setRowCount(0);
        SPlid.setText(TableClick);
        percent.setText(TableClick1);
         try {
            sList = p.queryViewParti_Sports(TableClick);
          
            for (int i=0;i<sList.size();i++){
            model1.addRow(new Object[]{});
            part.setValueAt(sList.get(i).getId(), i, 0);
            part.setValueAt(sList.get(i).getFullname(), i, 1);
            part.setValueAt(sList.get(i).getGender(), i, 2);
            part.setValueAt(sList.get(i).getTName(), i, 3);
           
        }
         }catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
         }
    }//GEN-LAST:event_speventMouseClicked

    private void teamsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teamsMouseClicked
        // TODO add your handling code here:
        int row = teams.getSelectedRow();
        String TableClick = (teams.getModel().getValueAt(row, 0).toString());
        query_participant_details QTN = new query_participant_details();
        teamid.setText(TableClick);
        try {
            
            timage.setText("");
            QTN._query_TeamImageSport(TableClick);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_teamsMouseClicked

    private void partMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_partMouseClicked
        // TODO add your handling code here:
        try{
        int row = part.getSelectedRow();
        String TableClick = (part.getModel().getValueAt(row, 0).toString());
        query_participant_details q = new query_participant_details();
        partid.setText(TableClick);
        pimage.setText("");
        q._query_PartImageSport(TableClick);
        
        }catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
         }
    }//GEN-LAST:event_partMouseClicked

    private void scoreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_scoreKeyReleased
        // TODO add your handling code here:
        NumberFormat formatter = new DecimalFormat("#0.00");
        double a = Double.parseDouble(score.getText());
        double b = Double.parseDouble(percent.getText());
        a = (b/100)*a;
        compute.setText(formatter.format(a));
    }//GEN-LAST:event_scoreKeyReleased

    private void scoreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_scoreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)||(c == KeyEvent.VK_PERIOD))) {
            getToolkit().beep();
            evt.consume();
        } else {
            // msg.setText("Can't Typed Char");
        }
    }//GEN-LAST:event_scoreKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)history.getModel();
        DefaultTableModel model1=(DefaultTableModel)spevent.getModel();
        int row = spevent.getSelectedRow();
        int row1 = teams.getSelectedRow();
        if(teamid.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please Select Team to be Score (Required)","Error",JOptionPane.ERROR_MESSAGE);
    }
        
        else if(SPlid.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please Select Event (Required)","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(ranks.getSelectedItem().equals("Select-Rank-:")){
           JOptionPane.showMessageDialog(null,"Please Select Rank (Required)","Error",JOptionPane.ERROR_MESSAGE); 
        }
        else if(score.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Please input Score (Required)","Error",JOptionPane.ERROR_MESSAGE); 
        }
        else{
        _AddCriteriaScore ACS = new _AddCriteriaScoreImplementation();
        ACS._addsport_score(Integer.parseInt(SPlid.getText()), Integer.parseInt(teamid.getText()), Double.parseDouble(score.getText()),cuturalid1.getText());
        JOptionPane.showMessageDialog(null,"Successfully  Saved");
        String TableClick1 = (spevent.getModel().getValueAt(row, 1).toString());
        String TableClick2 = (teams.getModel().getValueAt(row1, 1).toString());
        
        model.addRow(new Object[]{(String) ranks.getSelectedItem(),score.getText(),TableClick1,TableClick2});
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sport_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sport_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sport_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sport_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Sport_window().setVisible(true);
            }
        });
    }
    public void actionPerformed(ActionEvent e) {
        time1.setText(String.format("%tI:%<tM:%<tS %<Tp", new Date()));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SPlid;
    private javax.swing.JTextField compute;
    public static javax.swing.JLabel culturalname1;
    public static javax.swing.JLabel cuturalid1;
    private javax.swing.JLabel date1;
    private javax.swing.JTable history;
    private javax.swing.JPanel home;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel main;
    private javax.swing.JTable part;
    private javax.swing.JLabel partid;
    private javax.swing.JLabel percent;
    public static javax.swing.JLabel pimage;
    private javax.swing.JComboBox ranks;
    private javax.swing.JTextField score;
    private javax.swing.JPanel scoring;
    private javax.swing.JTable spevent;
    private javax.swing.JLabel teamid;
    private javax.swing.JTable teams;
    public static javax.swing.JLabel timage;
    private javax.swing.JLabel time1;
    // End of variables declaration//GEN-END:variables
}
